# Eksploracja danych — Laboratorium 1
## Python do analizy danych: przypomnienie

**Cel zajęć:** odświeżyć Pythona i poznać podstawy narzędzi, których będziemy używać przez cały semestr: **NumPy**, **pandas** i **matplotlib**.

**Plan:**
1. Python w pigułce
2. NumPy
3. pandas — pierwsze kroki
4. Wykresy w matplotlib

**Zadania** mają dwa poziomy:
- 🟢 **podstawowe** — obowiązkowe,
- 🔵 **dla ambitnych** — dodatkowe.

**Jak pracować:** w Colabie wybierz *Plik → Zapisz kopię na Dysku*, rozwiąż zadania w miejscach oznaczonych `# TODO`, a gotowy notatnik umieść w swoim repozytorium na GitHubie.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams.update({"figure.figsize": (7, 4), "font.size": 12})

---
# 1. Python w pigułce

In [2]:
# Listy, indeksowanie i wycinanie (slicing)
temperatury = [12.5, 14.0, 9.8, 17.3, 15.1]

print(temperatury[0])     # pierwszy element
print(temperatury[-1])    # ostatni element
print(temperatury[1:3])   # elementy o indeksach 1 i 2
print(len(temperatury))

12.5
15.1
[14.0, 9.8]
5

In [3]:
# Pętla for, enumerate i zip
dni = ["pon", "wt", "śr", "czw", "pt"]

for i, t in enumerate(temperatury):
    print(f"[{i}] -> {t}")

for dzien, t in zip(dni, temperatury):
    print(f"{dzien}: {t:.1f} °C")   # :.1f — jedna cyfra po przecinku

[0] -> 12.5
[1] -> 14.0
[2] -> 9.8
[3] -> 17.3
[4] -> 15.1
pon: 12.5 °C
wt: 14.0 °C
śr: 9.8 °C
czw: 17.3 °C
pt: 15.1 °C

In [4]:
# Słownik: klucz -> wartość
miasto = {"nazwa": "Łódź", "wojewodztwo": "łódzkie", "ludnosc_2021": 670_642}

print(miasto["nazwa"])
for klucz, wartosc in miasto.items():
    print(klucz, "=", wartosc)

Łódź
nazwa = Łódź
wojewodztwo = łódzkie
ludnosc_2021 = 670642

In [5]:
# Funkcja z docstringiem
def potega(lista, p):
    """
    Podnosi każdy element listy do potęgi p.

    Parametry:
    - lista (list): lista liczb,
    - p (int | float): wykładnik.

    Zwraca:
    - list: nowa lista z elementami podniesionymi do potęgi p.
    """
    wynik = []
    for x in lista:
        wynik.append(x ** p)
    return wynik


print(potega([1, 2, 3, 4], 3))
help(potega)   # w Jupyterze/Colabie także: potega?

[1, 8, 27, 64]
Help on function potega in module __main__:

potega(lista, p)
    Podnosi każdy element listy do potęgi p.

    Parametry:
    - lista (list): lista liczb,
    - p (int | float): wykładnik.

    Zwraca:
    - list: nowa lista z elementami podniesionymi do potęgi p.

### List comprehension

Zwięzły sposób tworzenia list:
```python
[wyrażenie for element in kolekcja if warunek]
```

In [6]:
print([x ** 2 for x in range(6)])
print([x ** 2 for x in range(6) if x % 2 == 0])

[0, 1, 4, 9, 16, 25]
[0, 4, 16]

### 🟢 Zadanie 1: średnia i mediana

Lista `dlugosc_zycia` zawiera oczekiwaną długość życia (w latach) w 14 krajach.

1. Napisz funkcję `srednia(liczby)`, która zwraca średnią arytmetyczną — **bez** używania `sum()` i NumPy (użyj pętli).
2. Napisz funkcję `mediana(liczby)`, która zwraca medianę. Pamiętaj o przypadku parzystej i nieparzystej liczby elementów. Wskazówka: `sorted()`.
3. Porównaj wyniki z `np.mean()` i `np.median()`.

🔵 **Dla ambitnych:** niech obie funkcje zgłaszają czytelny błąd (`raise ValueError(...)`), gdy lista jest pusta.

In [10]:
dlugosc_zycia = [81.8, 81.0, 82.6, 83.0, 81.8, 84.3, 82.8, 81.9, 82.2, 82.0, 82.7, 79.8, 83.3, 82.0]

In [11]:
def srednia(liczby):
    return sum(liczby) / len(liczby)


def mediana(liczby):
    posortowane = sorted(liczby)
    srodek = len(posortowane) // 2

    if len(posortowane) % 2 == 1:
        return posortowane[srodek]

    return (posortowane[srodek - 1] + posortowane[srodek]) / 2



print("moja średnia:", srednia(dlugosc_zycia), " NumPy:", np.mean(dlugosc_zycia))
print("moja mediana:", mediana(dlugosc_zycia), " NumPy:", np.median(dlugosc_zycia))

moja średnia: 82.22857142857143  NumPy: 82.22857142857143
moja mediana: 82.1  NumPy: 82.1

### 🟢 Zadanie 2: zliczanie

Napisz funkcję `zlicz(lista)`, która zwraca słownik: element → liczba jego wystąpień.

Przykład: `zlicz(["a", "b", "a", "c", "a"])` → `{"a": 3, "b": 1, "c": 1}`

Sprawdź ją na liście `oceny`. Która ocena występuje najczęściej?

In [8]:
oceny = [4, 3, 5, 4, 4, 2, 3, 5, 4, 3, 4, 5, 3, 4]

def zlicz(lista):
    wystapienia = {}

    for element in lista:
        if element in wystapienia:
            wystapienia[element] += 1
        else:
            wystapienia[element] = 1

    return wystapienia


zlicz(oceny)

{4: 6, 3: 4, 5: 3, 2: 1}

### 🟢 Zadanie 3: list comprehension

Dla listy `temperatury` (w °C) z początku notatnika:

1. Utwórz listę temperatur w stopniach Fahrenheita: $F = \frac{9}{5}C + 32$.
2. Utwórz listę tylko tych temperatur (w °C), które są wyższe niż 13 °C.
3. Utwórz listę napisów w postaci `"pon: 12.5 °C"` (wskazówka: `zip`).

Każdy punkt rozwiąż **jedną** linią.

In [12]:
# TODO

temperatury_f = [9 / 5 * temperatura + 32 for temperatura in temperatury]

temperatury_powyzej_13 = [temperatura for temperatura in temperatury if temperatura > 13]

temperatury_opisy = [f"{dzien}: {temperatura:.1f} °C" for dzien, temperatura in zip(dni, temperatury)]

---
# 2. NumPy

**NumPy** to podstawa obliczeń numerycznych w Pythonie — na nim zbudowane są pandas, scikit-learn i wiele innych bibliotek. Kluczowa idea: **wektoryzacja**, czyli operacje na całych tablicach naraz, bez pisania pętli.

In [13]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype, a.shape)

print(np.arange(0, 10, 2))       # od 0 do 10 (bez 10) co 2
print(np.linspace(0, 1, 5))      # 5 równo rozłożonych punktów od 0 do 1 (z 1)
print(np.zeros(3), np.ones(3))

[1 2 3 4 5] int64 (5,)
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0.] [1. 1. 1.]

### Lista ≠ tablica

Te same operatory działają inaczej na listach i na tablicach NumPy:

In [14]:
lista = [1, 2, 3]
tablica = np.array([1, 2, 3])

print("lista * 2   =", lista * 2)      # powtórzenie listy!
print("tablica * 2 =", tablica * 2)    # mnożenie każdego elementu
print("lista + lista     =", lista + lista)        # sklejenie list
print("tablica + tablica =", tablica + tablica)    # dodawanie element po elemencie

lista * 2   = [1, 2, 3, 1, 2, 3]
tablica * 2 = [2 4 6]
lista + lista     = [1, 2, 3, 1, 2, 3]
tablica + tablica = [2 4 6]

In [15]:
# Maski logiczne i agregacje
pomiary = np.array([7, 5, 4, 8, 4, 2, 9, 4, 100])

print("maska > 5:", pomiary > 5)
print("wartości > 5:", pomiary[pomiary > 5])
print("ile > 5:", (pomiary > 5).sum())

print("min, max:", pomiary.min(), pomiary.max())
print("średnia:", pomiary.mean())
print("mediana:", np.median(pomiary))
print("odchylenie standardowe:", pomiary.std())

maska > 5: [ True False False  True False False  True False  True]
wartości > 5: [  7   8   9 100]
ile > 5: 4
min, max: 2 100
średnia: 15.88888888888889
mediana: 5.0
odchylenie standardowe: 29.812169194789657

### Liczby losowe

Używamy **generatora** `np.random.default_rng()`. Ustalone ziarno (`seed`) daje powtarzalne wyniki.

In [16]:
rng = np.random.default_rng(seed=42)

print(rng.integers(1, 7, size=10))        # 10 rzutów kostką: liczby całkowite z [1, 7)
print(rng.uniform(0, 1, size=3))          # 3 liczby z rozkładu jednostajnego na [0, 1)
print(rng.normal(loc=0, scale=1, size=3)) # 3 liczby z rozkładu normalnego N(0, 1)

[1 5 4 3 3 6 1 5 2 1]
[0.97562235 0.7611397  0.78606431]
[-0.01680116 -0.85304393  0.87939797]

### 🟢 Zadanie 4: dlaczego NumPy?

Zsumuj liczby od 1 do 1 000 000 na **cztery sposoby** i zmierz czas każdego z nich magiczną komendą `%timeit`:

1. pętla `for`,
2. `sum()` na liście zbudowanej przez list comprehension,
3. `sum(range(...))`,
4. NumPy: `np.arange(...).sum()`.

Sprawdź, czy wszystkie dają ten sam wynik. Który sposób jest najszybszy i **dlaczego**? Odpowiedz w komórce tekstowej.

In [21]:
N = 1_000_000

def suma_petla():
    wynik = 0
    for liczba in range(1, N + 1):
        wynik += liczba
    return wynik


def suma_lista():
    return sum([liczba for liczba in range(1, N + 1)])


def suma_range():
    return sum(range(1, N + 1))


def suma_numpy():
    return np.arange(1, N + 1).sum()

# TODO: sprawdź, że wyniki są równe, a potem zmierz czasy, np.:
%timeit suma_petla()
%timeit suma_lista()
%timeit suma_range()
%timeit suma_numpy()

wyniki = [suma_petla(), suma_lista(), suma_range(), suma_numpy()]

print(wyniki)
print("Czy wszystkie wyniki są takie same?", len(set(wyniki)) == 1)

58.9 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
78 ms ± 17.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
28.8 ms ± 6.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
916 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[500000500000, 500000500000, 500000500000, np.int64(500000500000)]
Czy wszystkie wyniki są takie same? True

*Twoja odpowiedź:* …

Wszystkie cztery sposoby zwracają ten sam wynik: 500000500000. Najwolniejsza jest zwykle pętla for, ponieważ każda operacja dodawania wykonywana jest osobno w Pythonie. List comprehension jest szybsze, ale przy tym tworzy dodatkową listę w pamięci. sum(range(...)) jest bardzo szybkie, ponieważ funkcja sum() działa skutecznie dla obiektu range i nie tworzy całej listy. NumPy wykonuje obliczenia wektorowo w zoptymalizowanym kodzie, a więc jest dobre przy dużych tablicach i bardziej złożonych obliczeniach.

### 🟢 Zadanie 5: operacje na tablicach

Dana jest tablica `x` z pomiarami temperatury (°C).

1. Policz średnią, odchylenie standardowe, minimum i maksimum.
2. Wybierz pomiary wyższe od średniej. Ile ich jest?
3. **Normalizacja min–max:** przeskaluj `x` do przedziału $[0, 1]$: $\;x' = \dfrac{x - x_{\min}}{x_{\max} - x_{\min}}$
4. **Standaryzacja:** $\;z = \dfrac{x - \bar{x}}{s}$. Sprawdź, że wynik ma średnią ≈ 0 i odchylenie standardowe ≈ 1.

Wszystko bez pętli!

In [22]:
x = np.array([12.5, 14.0, 9.8, 17.3, 15.1, 11.2, 18.6, 16.0, 13.4, 10.9])

# TODO

srednia_x = np.mean(x)
odchylenie_x = np.std(x)
minimum_x = np.min(x)
maksimum_x = np.max(x)

print("Średnia:", srednia_x)
print("Odchylenie standardowe:", odchylenie_x)
print("Minimum:", minimum_x)
print("Maksimum:", maksimum_x)

powyzej_sredniej = x[x > srednia_x]

print("Pomiary wyższe od średniej:", powyzej_sredniej)
print("Liczba takich pomiarów:", len(powyzej_sredniej))

x_minmax = (x - minimum_x) / (maksimum_x - minimum_x)

print("Normalizacja min–max:", x_minmax)

x_standard = (x - srednia_x) / odchylenie_x

print("Standaryzacja:", x_standard)
print("Średnia po standaryzacji:", np.mean(x_standard))
print("Odchylenie po standaryzacji:", np.std(x_standard))

Średnia: 13.88
Odchylenie standardowe: 2.7352513595646015
Minimum: 9.8
Maksimum: 18.6
Pomiary wyższe od średniej: [14.  17.3 15.1 18.6 16. ]
Liczba takich pomiarów: 5
Normalizacja min–max: [0.30681818 0.47727273 0.         0.85227273 0.60227273 0.15909091
 1.         0.70454545 0.40909091 0.125     ]
Standaryzacja: [-0.50452402  0.04387165 -1.49163622  1.25034213  0.44602848 -0.97980026
  1.72561837  0.77506588 -0.17548661 -1.0894794 ]
Średnia po standaryzacji: -1.7763568394002506e-16
Odchylenie po standaryzacji: 1.0

### 🟢 Zadanie 6: rzuty kostką

1. Zasymuluj 10 000 rzutów kostką do gry (`rng.integers`).
2. Policz, ile razy wypadła każda liczba oczek (wskazówka: `np.unique(..., return_counts=True)`) i jaki to odsetek wszystkich rzutów.
3. Policz średnią liczbę oczek. Jakiej wartości się spodziewasz?

🔵 **Dla ambitnych:** zasymuluj 10 000 rzutów **dwiema** kostkami i policz rozkład sumy oczek. Która suma wypada najczęściej i dlaczego?

In [24]:
rng = np.random.default_rng(seed=1)

# TODO

rzuty = rng.integers(1, 7, size=10_000)

oczek, liczby = np.unique(rzuty, return_counts=True)
odsetki = liczby / len(rzuty) * 100

print("Liczba wyrzuconych oczek:", dict(zip(oczek, liczby)))
print("Odsetki:", dict(zip(oczek, odsetki.round(2))))
print("Średnia liczba oczek:", rzuty.mean())



#Dla ambitnych

print("\nRzuty 2 kostkami (10 000 prób):")

rzuty_2_kostkami = rng.integers(1, 7, size=(10_000, 2))
sumy = rzuty_2_kostkami.sum(axis=1)

sumy_oczek, liczby_sum = np.unique(sumy, return_counts=True)
odsetki_sum = liczby_sum / len(sumy) * 100

print("Rozkład sum:", dict(zip(sumy_oczek, liczby_sum)))
print("Odsetki:", dict(zip(sumy_oczek, odsetki_sum.round(2))))
print("Najczęstsza suma:", sumy_oczek[np.argmax(liczby_sum)])

Liczba wyrzuconych oczek: {np.int64(1): np.int64(1695), np.int64(2): np.int64(1634), np.int64(3): np.int64(1668), np.int64(4): np.int64(1628), np.int64(5): np.int64(1717), np.int64(6): np.int64(1658)}
Odsetki: {np.int64(1): np.float64(16.95), np.int64(2): np.float64(16.34), np.int64(3): np.float64(16.68), np.int64(4): np.float64(16.28), np.int64(5): np.float64(17.17), np.int64(6): np.float64(16.58)}
Średnia liczba oczek: 3.5012

Rzuty 2 kostkami (10 000 prób):
Rozkład sum: {np.int64(2): np.int64(297), np.int64(3): np.int64(596), np.int64(4): np.int64(883), np.int64(5): np.int64(1044), np.int64(6): np.int64(1328), np.int64(7): np.int64(1670), np.int64(8): np.int64(1436), np.int64(9): np.int64(1115), np.int64(10): np.int64(841), np.int64(11): np.int64(549), np.int64(12): np.int64(241)}
Odsetki: {np.int64(2): np.float64(2.97), np.int64(3): np.float64(5.96), np.int64(4): np.float64(8.83), np.int64(5): np.float64(10.44), np.int64(6): np.float64(13.28), np.int64(7): np.float64(16.7), np.int64(8): np.float64(14.36), np.int64(9): np.float64(11.15), np.int64(10): np.float64(8.41), np.int64(11): np.float64(5.49), np.int64(12): np.float64(2.41)}
Najczęstsza suma: 7

Najczęściej wypada suma 7, ponieważ jest najwięcej kombinacji, które dają w sumie 7 (1+6, 2+5, 3+4, 4+3, 5+2, 6+1).

---
# 3. pandas — pierwsze kroki

**pandas** służy do pracy z danymi tabelarycznymi. Podstawowe struktury:
- `Series` — jedna kolumna (wektor z etykietami),
- `DataFrame` — tabela, czyli zbiór kolumn o wspólnym indeksie.

### DataFrame ze słownika

In [25]:
dane = {
    "miasto": ["Warszawa", "Kraków", "Łódź", "Wrocław", "Poznań"],
    "ludnosc_2021": [1_860_281, 800_653, 670_642, 674_079, 546_859],
    "powierzchnia_km2": [517, 327, 293, 293, 262],
}
miasta = pd.DataFrame(dane)
miasta

     miasto  ludnosc_2021  powierzchnia_km2
0  Warszawa       1860281               517
1    Kraków        800653               327
2      Łódź        670642               293
3   Wrocław        674079               293
4    Poznań        546859               262

In [26]:
# Nowa kolumna obliczona z innych kolumn
miasta["gestosc"] = miasta["ludnosc_2021"] / miasta["powierzchnia_km2"]
miasta.sort_values("gestosc", ascending=False)

     miasto  ludnosc_2021  powierzchnia_km2      gestosc
0  Warszawa       1860281               517  3598.222437
1    Kraków        800653               327  2448.480122
3   Wrocław        674079               293  2300.610922
2      Łódź        670642               293  2288.880546
4    Poznań        546859               262  2087.248092

In [27]:
# Zapis do pliku CSV i ponowne wczytanie
miasta.to_csv("miasta.csv", index=False)
pd.read_csv("miasta.csv")

     miasto  ludnosc_2021  powierzchnia_km2      gestosc
0  Warszawa       1860281               517  3598.222437
1    Kraków        800653               327  2448.480122
2      Łódź        670642               293  2288.880546
3   Wrocław        674079               293  2300.610922
4    Poznań        546859               262  2087.248092

### Prawdziwy zbiór danych: `tips`

Zbiór `tips` zawiera 244 rachunki z restauracji, zapisane przez kelnera w ciągu kilku tygodni.

| kolumna | znaczenie |
|---|---|
| `total_bill` | kwota rachunku (USD) |
| `tip` | napiwek (USD) |
| `sex` | płeć płacącego |
| `smoker` | czy przy stoliku palono |
| `day` | dzień tygodnia |
| `time` | pora: lunch / obiad |
| `size` | liczba osób przy stoliku |

In [28]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Pierwszy rzut oka na dane

In [29]:
print(df.shape)     # (liczba wierszy, liczba kolumn)
df.info()           # typy kolumn i liczba niepustych wartości

(244, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [30]:
df.describe()       # statystyki opisowe kolumn liczbowych

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Wybieranie kolumn i wierszy

In [31]:
df["tip"].head()                    # jedna kolumna -> Series

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [32]:
df[["total_bill", "tip"]].head()    # kilka kolumn -> DataFrame (podwójne nawiasy!)

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31
4       24.59  3.61

In [33]:
print(df["tip"].mean(), df["tip"].max())   # metody kolumny

2.99827868852459 10.0

### `loc` czy `iloc`?

- `iloc` — wybiera po **pozycji** (0, 1, 2, …),
- `loc` — wybiera po **etykiecie indeksu**.

Póki indeks to 0, 1, 2, …, oba dają to samo. Różnica wychodzi na jaw po posortowaniu:

In [34]:
posortowane = df.sort_values("tip", ascending=False)
posortowane.head(3)

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
23        39.42   7.58  Male     No  Sat  Dinner     4

In [35]:
print("iloc[0] — pierwszy wiersz po posortowaniu (najwyższy napiwek):")
print(posortowane.iloc[0], "\n")

print("loc[0] — wiersz o etykiecie 0 (pierwszy rachunek w danych):")
print(posortowane.loc[0])

iloc[0] — pierwszy wiersz po posortowaniu (najwyższy napiwek):
total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

loc[0] — wiersz o etykiecie 0 (pierwszy rachunek w danych):
total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

### Filtrowanie

Warunki łączymy operatorami `&` (i), `|` (lub), `~` (nie) — każdy warunek **w nawiasach**.

In [37]:
duze_rachunki = df[df["total_bill"] > 40]
duze_rachunki

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4

In [38]:
sobota_obiad = df[(df["day"] == "Sat") & (df["time"] == "Dinner")]
print(len(sobota_obiad), "rachunków w sobotę na obiedzie")

87 rachunków w sobotę na obiedzie

In [39]:
# Z .loc: wiersze spełniające warunek i wybrane kolumny
df.loc[df["size"] >= 5, ["total_bill", "tip", "size"]]

     total_bill   tip  size
125       29.80  4.20     6
141       34.30  6.70     6
142       41.19  5.00     5
143       27.05  5.00     6
155       29.85  5.14     5
156       48.17  5.00     6
185       20.69  5.00     5
187       30.46  2.00     5
216       28.15  3.00     5

In [40]:
df["day"].value_counts()    # ile razy występuje każda wartość

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### 🟢 Zadanie 7: pytania do zbioru `tips`

Odpowiedz kodem:

1. Ile wierszy i kolumn ma zbiór? Jakie są nazwy kolumn?
2. Jaki jest średni, najmniejszy i największy rachunek?
3. Ile rachunków pochodzi z niedzieli (`"Sun"`)?
4. Pokaż 5 najwyższych rachunków.
5. Dodaj kolumnę `tip_pct` — napiwek jako procent rachunku. Jaki jest średni `tip_pct`?
6. Ile rachunków ma napiwek wyższy niż 20% rachunku?

🔵 **Dla ambitnych:**

7. Jaki jest średni `tip_pct` dla lunchu, a jaki dla obiadu? (Użyj filtrowania.)
8. Dodaj kolumnę `rachunek_na_osobe`. Przy którym stoliku rachunek na osobę był najwyższy?

In [41]:
# TODO

import seaborn as sns

tips = sns.load_dataset("tips")

print("Liczba wierszy i kolumn:", tips.shape)
print("Nazwy kolumn:", list(tips.columns))

print("Średni rachunek:", tips["total_bill"].mean())
print("Najmniejszy rachunek:", tips["total_bill"].min())
print("Największy rachunek:", tips["total_bill"].max())

print("Liczba rachunków z niedzieli:", (tips["day"] == "Sun").sum())

print("5 najwyższych rachunków:")
print(tips.nlargest(5, "total_bill"))

tips["tip_pct"] = tips["tip"] / tips["total_bill"] * 100

print("Średni procent napiwku:", tips["tip_pct"].mean())

print("Liczba rachunków z napiwkiem powyżej 20%:", (tips["tip_pct"] > 20).sum())

print("Średni tip_pct dla lunchu:", tips.loc[tips["time"] == "Lunch", "tip_pct"].mean())
print("Średni tip_pct dla obiadu:", tips.loc[tips["time"] == "Dinner", "tip_pct"].mean())

tips["rachunek_na_osobe"] = tips["total_bill"] / tips["size"]

najwyzszy = tips.loc[tips["rachunek_na_osobe"].idxmax()]

print("Najwyższy rachunek na osobę:")
print(najwyzszy)

Liczba wierszy i kolumn: (244, 7)
Nazwy kolumn: ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']
Średni rachunek: 19.78594262295082
Najmniejszy rachunek: 3.07
Największy rachunek: 50.81
Liczba rachunków z niedzieli: 76
5 najwyższych rachunków:
     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3
Średni procent napiwku: 16.08025817225047
Liczba rachunków z napiwkiem powyżej 20%: 39
Średni tip_pct dla lunchu: 16.412792816250498
Średni tip_pct dla obiadu: 15.951778877977734
Najwyższy rachunek na osobę:
total_bill              40.55
tip                       3.0
sex                      Male
smoker                    Yes
day                       Sun
time                   Dinner
size                        2
tip_pct              7.398274
rachunek_na_osobe      20.275
Name: 184, dtype: object

### 🟢 Zadanie 8: ludność Warszawy i Łodzi

| Rok | Warszawa | Łódź |
|---|---|---|
| 2002 | 1 672 000 | 789 318 |
| 2011 | 1 700 612 | 728 892 |
| 2015 | 1 740 000 | brak danych |
| 2021 | 1 860 281 | 670 642 |

1. Przekształć tabelę w słownik i utwórz z niego DataFrame. Brak danych zapisz jako `np.nan`.
2. Zapisz DataFrame do pliku `ludnosc.csv` i wczytaj go ponownie.
3. Sprawdź typy kolumn (`dtypes`) i liczbę braków (`isna().sum()`).
4. Policz zmianę procentową liczby ludności obu miast między 2011 a 2021 r.

🔵 **Dla ambitnych:** co się stanie z typem kolumny `Łódź`, jeśli zamiast `np.nan` wpiszesz tekst `"brak danych"`? Jak to naprawić? (Wskazówka: `pd.to_numeric(..., errors="coerce")`.)

In [ ]:
# TODO

---
# 4. Wykresy w matplotlib

Używamy stylu obiektowego:
```python
fig, ax = plt.subplots()   # fig — cały rysunek, ax — jeden układ współrzędnych
ax.plot(...)
ax.set_xlabel(...)
```

In [ ]:
# Wykres liniowy
x = np.linspace(0, 2 * np.pi, 100)

fig, ax = plt.subplots()
ax.plot(x, np.sin(x), label="sin(x)")
ax.plot(x, np.cos(x), "--", label="cos(x)")
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("Funkcje trygonometryczne")
ax.grid(True)
ax.legend();

In [ ]:
# Kilka paneli obok siebie; skala logarytmiczna
x = np.linspace(0.1, 10, 50)

fig, axs = plt.subplots(1, 2, figsize=(10, 4))
axs[0].plot(x, np.exp(x))
axs[0].set_title("skala liniowa")
axs[1].plot(x, np.exp(x))
axs[1].set_yscale("log")
axs[1].set_title("skala logarytmiczna")
for ax in axs:
    ax.set_xlabel("x")
    ax.set_ylabel("exp(x)")
fig.tight_layout()

In [ ]:
# Wykres punktowy
fig, ax = plt.subplots()
ax.scatter(df["total_bill"], df["tip"], s=15, alpha=0.7)
ax.set_xlabel("rachunek [USD]")
ax.set_ylabel("napiwek [USD]")
ax.set_title("Rachunek a napiwek");

In [ ]:
# Wykres słupkowy
liczba = df["day"].value_counts()

fig, ax = plt.subplots()
ax.bar(liczba.index, liczba.values)
ax.set_xlabel("dzień")
ax.set_ylabel("liczba rachunków")
ax.set_title("Liczba rachunków w poszczególne dni");

In [ ]:
# Histogram — rozkład jednej zmiennej liczbowej
fig, ax = plt.subplots()
ax.hist(df["total_bill"], bins=20, edgecolor="white")
ax.set_xlabel("rachunek [USD]")
ax.set_ylabel("liczba rachunków")
ax.set_title("Rozkład rachunków");

### 🟢 Zadanie 9: lunch czy obiad?

Porównaj rozkład rachunków (`total_bill`) na lunchu i na obiedzie.

1. Narysuj dwa histogramy obok siebie (rysunek 10 × 4): lewy dla lunchu (`"Lunch"`), prawy dla obiadu (`"Dinner"`).
2. Oba histogramy muszą mieć **te same przedziały** (`bins=np.arange(0, 60, 5)`) i **wspólne osie** (`plt.subplots(..., sharex=True, sharey=True)`) — inaczej porównanie będzie mylące.
3. Na każdym panelu zaznacz średni rachunek pionową linią przerywaną (`ax.axvline(...)`) i podpisz ją w legendzie.
4. Dodaj tytuły i opisy osi z jednostkami.
5. W komórce tekstowej odpowiedz: kiedy rachunki są wyższe? Ile jest rachunków w każdej grupie?

🔵 **Dla ambitnych:** narysuj oba rozkłady na **jednym** wykresie (półprzezroczyste, `alpha=0.5`). Porównaj wersję z liczebnościami i z `density=True`. Dlaczego przy grupach różnej wielkości lepiej użyć `density=True`?

In [ ]:
# TODO

*Twoja odpowiedź:* …

In [ ]:
# 🔵 TODO

### 🟢 Zadanie 10: wykresy dla `tips` i ludności

1. Narysuj histogram napiwków (`tip`). Wypróbuj `bins` = 5, 20 i 50 — trzy panele obok siebie. Która liczba przedziałów najlepiej pokazuje kształt rozkładu?
2. Narysuj wykres liniowy liczby ludności Warszawy i Łodzi z zadania 8 (oba miasta na jednym wykresie, z legendą i znacznikami `marker="o"`).
3. Każdy wykres musi mieć tytuł i opisy osi z jednostkami.

In [ ]:
# TODO

### 🔵 Zadanie 11 (dla ambitnych): rozkład normalny

1. Napisz funkcję gęstości rozkładu normalnego:
$$ f(x; \mu, \sigma) = \frac{1}{\sigma\sqrt{2\pi}} \exp\left(-\frac{(x-\mu)^2}{2\sigma^2}\right) $$
2. Dla trzech par $(\mu, \sigma)$: (0, 1), (0, 2), (2, 1) wygeneruj po 10 000 liczb (`rng.normal`) i narysuj ich histogram (`density=True`) razem z krzywą gęstości policzoną ze wzoru.
3. Trzy wykresy jeden pod drugim, każdy z tytułem zawierającym $\mu$ i $\sigma$, opisami osi i legendą.

In [ ]:
# TODO

---
# Podsumowanie

Po tych zajęciach potrafisz:
- [ ] posługiwać się listami, słownikami, pętlami, funkcjami i list comprehension,
- [ ] tworzyć tablice NumPy, liczyć na nich bez pętli i losować liczby,
- [ ] wczytać dane do pandas, obejrzeć je (`head`, `info`, `describe`) i wybierać wiersze oraz kolumny,
- [ ] tworzyć nowe kolumny i zapisywać dane do pliku CSV,
- [ ] narysować wykres liniowy, punktowy, słupkowy i histogram — z opisami osi.

**Do oddania:** ten notatnik z rozwiązanymi zadaniami 🟢 w Twoim repozytorium na GitHubie.